### ISSUE TITLE
Dependency error in Account Service

### ISSUE THREAD

**Issue by Sharjeel50** [we-3hackathon/bdonor#13]
Error: Error creating bean with name 'accountService': Unsatisfied dependency expressed through field 'UserRepo'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'userRepository': Invocation of init method failed; nested exception is org.springframework.data.mapping.PropertyReferenceException: No property firstName found for type User! Did you mean '_firstname'?

**Comment by Sumite321** [comment]
Now fixed. Get user by first name also OK now. Available on service-a.
