### ISSUE TITLE
account-service checkCredentials error

### ISSUE THREAD

**Issue by Sharjeel50** [we-3hackathon/bdonor#22]
Getting error Error - "No property email found for type User! Did you mean '_email'?" when running  method.

**Comment by Sumite321** [comment]
https://github.com/we-3hackathon/bdonor/blob/c88ab636f4a86c3a71f69cc6d2b22af728c6df88/account-service/src/main/java/com/bdonor/accountservice/Controller/AccountController.java#L55-L56

1.  you have `@PathVariable String _email, String _password`, you missing another `@PathVariable` ?
2.  `_email` doesnt match `/checkCredentials/{email}/{password}`?

Try it

**Comment by Sharjeel50** [comment]
changing "_email" to "email" in the `User` class fixed the error.

**Comment by Sharjeel50** [comment]
resolved #22
