### ISSUE TITLE
Autowiring issue

### ISSUE THREAD

**Issue by Sharjeel50** [we-3hackathon/bdonor#34]
"CrudRepo" giving error when autowired in class "DynamoRepo"

Given error `Field crudRepo in com.bdonor.accountservice.Repository.DynamoRepo required a bean of type 'com.bdonor.accountservice.Repository.CrudRepo' that could not be found.`

**Comment by Sumite321** [comment]
Fix:
* Declare latest version for dependency on pom.xml
